name: crypto_market_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0-77.0.dev
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  flutter_spinkit: ^5.2.1
  dio: ^5.6.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: mr
      fonts:
        - asset: assets/fonts/mh.ttf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/CryptoMarket_Lgo.png"
  min_sdk_android: 21        